import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Download, FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";

export default function ExportReports({ monitors, alerts }) {
  const [exporting, setExporting] = useState(false);

  const exportToCSV = () => {
    setExporting(true);
    try {
      // Prepare CSV data
      const headers = ['Wallet Address', 'Blockchain', 'Risk Score', 'Balance USD', 'Total Transactions', 'Status', 'Last Activity'];
      const rows = monitors.map(m => [
        m.wallet_address,
        m.blockchain,
        m.risk_score || 0,
        m.balance_usd?.toFixed(2) || '0.00',
        m.total_transactions || 0,
        m.monitoring_status,
        m.last_transaction_date ? new Date(m.last_transaction_date).toLocaleDateString() : 'N/A'
      ]);

      const csvContent = [
        headers.join(','),
        ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
      ].join('\n');

      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `crypto-tracker-report-${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();

      toast.success("📥 CSV exported successfully");
    } catch (error) {
      toast.error("Export failed: " + error.message);
    }
    setExporting(false);
  };

  const exportToPDF = async () => {
    setExporting(true);
    try {
      // Create formatted text report
      const reportText = `
BLOCKCHAIN WALLET TRACKING REPORT
Generated: ${new Date().toLocaleString()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Tracked Wallets: ${monitors.length}
High Risk Wallets: ${monitors.filter(m => m.risk_score > 70).length}
Active Monitors: ${monitors.filter(m => m.monitoring_status === 'active').length}
Total Alerts: ${alerts.length}

WALLET DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${monitors.map((m, i) => `
${i + 1}. WALLET: ${m.wallet_address}
   Blockchain: ${m.blockchain.toUpperCase()}
   Risk Score: ${m.risk_score}/100
   Balance: $${m.balance_usd?.toFixed(2) || '0.00'}
   Transactions: ${m.total_transactions || 0}
   Status: ${m.monitoring_status}
   Last Activity: ${m.last_transaction_date ? new Date(m.last_transaction_date).toLocaleDateString() : 'N/A'}
   ${m.exchange_detected ? `⚠ Exchange Detected: ${m.exchange_name}` : ''}
   ${m.mixer_detected ? '⚠ Mixer Usage Detected' : ''}
   ${m.risk_indicators?.length > 0 ? `Risk Indicators: ${m.risk_indicators.join(', ')}` : ''}
`).join('\n')}

RECENT ALERTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${alerts.slice(0, 20).map((a, i) => `
${i + 1}. [${a.severity.toUpperCase()}] ${a.title}
   Wallet: ${a.wallet_address}
   Type: ${a.alert_type}
   ${a.amount_usd ? `Amount: $${a.amount_usd.toFixed(2)}` : ''}
   Time: ${new Date(a.created_date).toLocaleString()}
   Status: ${a.status}
`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Report generated by SafeNestt Crypto Tracker
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      `.trim();

      const blob = new Blob([reportText], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `crypto-tracker-report-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();

      toast.success("📥 PDF report exported");
    } catch (error) {
      toast.error("Export failed: " + error.message);
    }
    setExporting(false);
  };

  return (
    <div className="flex items-center gap-3">
      <Button
        onClick={exportToCSV}
        disabled={exporting || monitors.length === 0}
        variant="outline"
        className="border-cyan-500/30 text-cyan-400"
      >
        {exporting ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Exporting...
          </>
        ) : (
          <>
            <Download className="w-4 h-4 mr-2" />
            Export CSV
          </>
        )}
      </Button>
      <Button
        onClick={exportToPDF}
        disabled={exporting || monitors.length === 0}
        variant="outline"
        className="border-green-500/30 text-green-400"
      >
        {exporting ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Exporting...
          </>
        ) : (
          <>
            <FileText className="w-4 h-4 mr-2" />
            Export Report
          </>
        )}
      </Button>
    </div>
  );
}