import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Loader2, Printer, RefreshCw, Shield, FileText, Download, ExternalLink } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

export default function CryptoIntelligenceReport({ caseData }) {
  const [coverLetter, setCoverLetter] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const generateContentMutation = useMutation({
    mutationFn: async () => {
      const prompt = `
        You are a senior crypto investigator. Write a formal cover letter for a law enforcement referral (FBI/IC3) regarding a cryptocurrency fraud case.
        
        Case Details:
        - SafeNest Case ID: ${caseData.case_number}
        - Victim: ${caseData.victim_name}
        - Loss: $${caseData.amount_stolen_usd?.toLocaleString()}
        - Type: ${caseData.fraud_type}
        - Scammer: ${caseData.scammer_info?.name || 'Unknown'}
        - Blockchain: ${caseData.blockchain}
        
        The letter should:
        1. Summarize the incident briefly.
        2. Highlight that technical evidence (IPs, wallets) is attached.
        3. Request immediate asset freezing if applicable.
        4. Be addressed to "Federal Law Enforcement / Exchange Compliance Team".
        5. Leave placeholders for Admin Name.
      `;

      const response = await base44.integrations.Core.InvokeLLM({
        prompt,
        response_json_schema: { type: "object", properties: { cover_letter: { type: "string" } } }
      });
      return response.cover_letter;
    },
    onSuccess: (data) => {
      setCoverLetter(data);
      toast.success("Cover letter generated");
    },
    onError: () => toast.error("Failed to generate cover letter")
  });

  useEffect(() => {
    if (!coverLetter && !isGenerating) {
      setIsGenerating(true);
      generateContentMutation.mutate(null, { onSettled: () => setIsGenerating(false) });
    }
  }, []);

  const handlePrint = () => {
    window.print();
  };

  const wallets = [
    ...(caseData.monitored_wallets || []),
    ...(caseData.scammer_info?.wallet_addresses || []),
    ...(caseData.suspect_details?.wallet_addresses || [])
  ].filter((v, i, a) => a.indexOf(v) === i);

  return (
    <div className="space-y-6">
      {/* Controls - Hidden when printing */}
      <div className="flex justify-between items-center p-4 bg-[#0f1419] rounded-lg border border-cyan-500/20 print:hidden">
        <div>
          <h2 className="text-white font-bold flex items-center gap-2">
            <Shield className="w-5 h-5 text-cyan-400" />
            Crypto Intelligence Report
          </h2>
          <p className="text-gray-400 text-sm">Law Enforcement & Compliance Ready</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => generateContentMutation.mutate()} disabled={isGenerating}>
            <RefreshCw className={`w-4 h-4 mr-2 ${isGenerating ? 'animate-spin' : ''}`} />
            Regenerate AI Content
          </Button>
          <Button onClick={handlePrint} className="bg-cyan-600 hover:bg-cyan-700">
            <Printer className="w-4 h-4 mr-2" />
            Print / Export PDF
          </Button>
        </div>
      </div>

      {/* Report Content */}
      <div className="bg-white text-black p-8 max-w-[210mm] mx-auto min-h-[297mm] shadow-xl print:shadow-none print:p-0">
        
        {/* Header */}
        <div className="border-b-2 border-slate-800 pb-6 mb-8 flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 uppercase tracking-wider">Confidential Intelligence Report</h1>
            <p className="text-slate-600 font-semibold mt-1">Cryptocurrency Fraud Investigation Unit</p>
            <p className="text-slate-500 text-sm">Generated by SafeNestT Security Platform</p>
          </div>
          <div className="text-right">
            <p className="font-mono text-sm text-slate-500">Date: {new Date().toLocaleDateString()}</p>
            <p className="font-mono text-lg font-bold text-slate-800">ID: {caseData.case_number}</p>
            <Badge className="bg-red-100 text-red-800 border-red-200 mt-2">LAW ENFORCEMENT SENSITIVE</Badge>
          </div>
        </div>

        {/* 1. Victim & Case Summary */}
        <section className="mb-8">
          <h3 className="text-lg font-bold text-slate-800 border-b border-slate-300 pb-2 mb-4 uppercase">1. Victim & Case Summary</h3>
          <div className="grid grid-cols-2 gap-6 text-sm">
            <div>
              <p className="text-slate-500 uppercase text-xs font-bold">Victim Details</p>
              <p className="font-semibold">{caseData.victim_name}</p>
              <p>{caseData.victim_email}</p>
              <p>{caseData.victim_phone}</p>
            </div>
            <div>
              <p className="text-slate-500 uppercase text-xs font-bold">Loss Summary</p>
              <p className="font-semibold text-red-700 text-lg">${caseData.amount_stolen_usd?.toLocaleString()} USD</p>
              <p>{caseData.cryptocurrency} on {caseData.blockchain}</p>
              <p>Type: {caseData.fraud_type?.replace('_', ' ').toUpperCase()}</p>
            </div>
          </div>
          <div className="mt-4">
            <p className="text-slate-500 uppercase text-xs font-bold mb-1">Incident Description</p>
            <p className="text-sm text-slate-700 leading-relaxed bg-slate-50 p-3 rounded border border-slate-100">
              {caseData.description}
            </p>
          </div>
          {caseData.timeline && caseData.timeline.length > 0 && (
            <div className="mt-4">
              <p className="text-slate-500 uppercase text-xs font-bold mb-1">Key Timeline</p>
              <ul className="list-disc list-inside text-sm text-slate-700">
                {caseData.timeline.slice(0, 5).map((t, i) => (
                  <li key={i}><span className="font-mono text-xs text-slate-500">{new Date(t.date).toLocaleDateString()}</span> - {t.event}</li>
                ))}
              </ul>
            </div>
          )}
        </section>

        {/* 2. IC3 Complaint Section */}
        <section className="mb-8 break-inside-avoid">
          <h3 className="text-lg font-bold text-slate-800 border-b border-slate-300 pb-2 mb-4 uppercase">2. IC3 Complaint Status</h3>
          <div className="bg-slate-50 border border-slate-200 p-4 rounded">
            <div className="flex items-center gap-4">
              <div className="flex-1">
                <p className="text-sm font-bold text-slate-700">IC3 Complaint Number</p>
                <p className="text-xl font-mono text-slate-900">{caseData.ic3_complaint_number || "PENDING / NOT FILED"}</p>
              </div>
              <div className="flex-1 border-l border-slate-200 pl-4">
                <p className="text-sm font-bold text-slate-700">Federal Case Number</p>
                <p className="text-font-mono text-slate-900">{caseData.federal_case_number || "N/A"}</p>
              </div>
            </div>
            <div className="mt-3 pt-3 border-t border-slate-200">
              <p className="text-xs text-slate-500 mb-1">Supplemental Report Status</p>
              <p className="text-sm text-slate-700">
                A supplemental technical report is attached below for submission to the FBI IC3 portal.
                This document contains verified blockchain forensics not present in the initial filing.
              </p>
            </div>
          </div>
        </section>

        {/* 3. Blockchain Analysis */}
        <section className="mb-8 break-inside-avoid">
          <h3 className="text-lg font-bold text-slate-800 border-b border-slate-300 pb-2 mb-4 uppercase">3. On-Chain Analysis</h3>
          
          <div className="mb-4">
            <p className="text-slate-500 uppercase text-xs font-bold mb-2">Identified Suspect Wallets</p>
            {wallets.length > 0 ? (
              <div className="space-y-2">
                {wallets.map((w, i) => (
                  <div key={i} className="font-mono text-xs bg-slate-100 p-2 rounded border border-slate-200 text-slate-800 break-all">
                    {w}
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-slate-500 italic">No specific wallet addresses identified yet.</p>
            )}
          </div>

          {caseData.transaction_hashes && caseData.transaction_hashes.length > 0 && (
            <div className="mb-4">
              <p className="text-slate-500 uppercase text-xs font-bold mb-2">Critical Transactions</p>
              <div className="space-y-1">
                {caseData.transaction_hashes.map((tx, i) => (
                  <div key={i} className="font-mono text-xs text-slate-600 break-all">
                    • {tx}
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="bg-yellow-50 border border-yellow-200 p-3 rounded mt-4">
            <p className="text-xs font-bold text-yellow-800 uppercase mb-1">Risk Assessment</p>
            <p className="text-sm text-yellow-900">
              Funds detected on {caseData.blockchain || 'blockchain'}. 
              High risk of dissipation through mixers or non-compliant exchanges. 
              Immediate freeze requested.
            </p>
          </div>
        </section>

        {/* 4. Scammer Profile */}
        <section className="mb-8 break-inside-avoid">
          <h3 className="text-lg font-bold text-slate-800 border-b border-slate-300 pb-2 mb-4 uppercase">4. Scammer Digital Profile</h3>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div className="bg-slate-50 p-3 rounded border border-slate-200">
              <p className="text-xs font-bold text-slate-500 uppercase mb-2">Contact Methods</p>
              <div className="space-y-1">
                <p><span className="font-semibold">Name/Alias:</span> {caseData.scammer_info?.name || caseData.suspect_details?.primary_suspect?.name || 'Unknown'}</p>
                <p><span className="font-semibold">Email:</span> {caseData.scammer_info?.email || 'N/A'}</p>
                <p><span className="font-semibold">Phone:</span> {caseData.scammer_info?.phone || 'N/A'}</p>
                <p><span className="font-semibold">Website:</span> {caseData.scammer_info?.website || 'N/A'}</p>
              </div>
            </div>
            <div className="bg-slate-50 p-3 rounded border border-slate-200">
              <p className="text-xs font-bold text-slate-500 uppercase mb-2">Digital Footprint</p>
              {caseData.scammer_info?.social_media?.length > 0 ? (
                <ul className="list-disc list-inside">
                  {caseData.scammer_info.social_media.map((sm, i) => (
                    <li key={i}>{typeof sm === 'string' ? sm : `${sm.platform}: ${sm.profile}`}</li>
                  ))}
                </ul>
              ) : (
                <p className="italic text-slate-500">No social media profiles linked.</p>
              )}
            </div>
          </div>
        </section>

        {/* 5. Evidence */}
        <section className="mb-8 break-inside-avoid">
          <h3 className="text-lg font-bold text-slate-800 border-b border-slate-300 pb-2 mb-4 uppercase">5. Evidence Attachments</h3>
          {caseData.evidence_files?.length > 0 ? (
            <table className="w-full text-sm text-left">
              <thead>
                <tr className="border-b border-slate-200">
                  <th className="py-2 font-semibold text-slate-600">File Name</th>
                  <th className="py-2 font-semibold text-slate-600">Type</th>
                  <th className="py-2 font-semibold text-slate-600">Date</th>
                </tr>
              </thead>
              <tbody>
                {caseData.evidence_files.map((ev, i) => (
                  <tr key={i} className="border-b border-slate-100">
                    <td className="py-2 text-slate-800">{ev.name}</td>
                    <td className="py-2 text-slate-600 uppercase text-xs">{ev.type || 'Document'}</td>
                    <td className="py-2 text-slate-600 font-mono text-xs">{new Date(ev.uploaded_date).toLocaleDateString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <p className="text-sm text-slate-500 italic">No files attached to this digital report.</p>
          )}
        </section>

        {/* 6. Recommended Actions */}
        <section className="mb-8 break-inside-avoid">
          <h3 className="text-lg font-bold text-slate-800 border-b border-slate-300 pb-2 mb-4 uppercase">6. Recommended Actions</h3>
          <ul className="list-decimal list-inside text-sm text-slate-800 space-y-2">
            <li><span className="font-semibold">Immediate Asset Freeze:</span> Contact identified exchanges to freeze suspect wallets listed in Section 3.</li>
            <li><span className="font-semibold">IC3 Filing:</span> If not yet filed, submit this report to ic3.gov immediately.</li>
            <li><span className="font-semibold">Preservation Letter:</span> Issue preservation letters to email providers and social platforms listed in Section 4.</li>
            <li><span className="font-semibold">Chain Analysis:</span> Continue monitoring suspect addresses for movement to off-ramps.</li>
          </ul>
        </section>

        {/* 7. Cover Letter */}
        <section className="break-before-page">
          <h3 className="text-lg font-bold text-slate-800 border-b border-slate-300 pb-2 mb-4 uppercase">7. Law Enforcement Cover Letter</h3>
          <div className="bg-white border border-slate-200 p-8 shadow-sm print:shadow-none print:border-0 print:p-0">
            {isGenerating ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="w-8 h-8 text-slate-400 animate-spin" />
                <span className="ml-2 text-slate-500">Drafting cover letter...</span>
              </div>
            ) : (
              <Textarea
                value={coverLetter}
                onChange={(e) => setCoverLetter(e.target.value)}
                className="min-h-[500px] font-serif text-base leading-relaxed border-0 focus-visible:ring-0 p-0 resize-none w-full"
                placeholder="Cover letter content..."
              />
            )}
          </div>
        </section>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t border-slate-200 text-center text-xs text-slate-400 print:fixed print:bottom-0 print:left-0 print:w-full print:bg-white print:pt-2 print:pb-4">
          <p>CONFIDENTIAL - PROPRIETARY - LAW ENFORCEMENT SENSITIVE</p>
          <p>Generated by SafeNestT Intelligence System • {new Date().toISOString()}</p>
        </div>
      </div>
    </div>
  );
}