import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { 
  Send, Building2, Shield, FileText, Download, ExternalLink, 
  CheckCircle, AlertTriangle, Loader2, Mail, Globe
} from "lucide-react";
import { toast } from "sonner";

const FEDERAL_AGENCIES = [
  {
    id: 'ic3',
    name: 'FBI IC3',
    fullName: 'FBI Internet Crime Complaint Center',
    icon: Shield,
    color: 'blue',
    url: 'https://www.ic3.gov/Home/FileComplaint',
    description: 'Primary agency for crypto fraud and internet crimes',
    requirements: ['Case Summary', 'Transaction Log', 'Evidence Package']
  },
  {
    id: 'secret_service',
    name: 'Secret Service',
    fullName: 'U.S. Secret Service - Cyber Division',
    icon: Shield,
    color: 'purple',
    url: 'https://www.secretservice.gov/investigation',
    description: 'Financial crimes and large-scale fraud',
    requirements: ['Case Summary', 'Transaction Analysis', 'Scammer Profile']
  },
  {
    id: 'ftc',
    name: 'FTC',
    fullName: 'Federal Trade Commission',
    icon: Building2,
    color: 'green',
    url: 'https://reportfraud.ftc.gov/',
    description: 'Consumer protection and fraud reporting',
    requirements: ['Victim Statement', 'Case Summary']
  },
  {
    id: 'local_pd',
    name: 'Local Police',
    fullName: 'Local Police Department',
    icon: Shield,
    color: 'cyan',
    url: null,
    description: 'File local police report for documentation',
    requirements: ['Case Summary', 'Victim Statement', 'Evidence Package']
  }
];

const DOCUMENT_NAMES = {
  case_summary: 'Case Summary',
  victim_statement: 'Victim Statement',
  transaction_log: 'Transaction Log',
  transaction_analysis: 'Transaction Analysis',
  scammer_profile: 'Scammer Profile',
  evidence_package: 'Evidence Package'
};

export default function FederalSubmission({ caseData, documents, isDialog, onClose }) {
  const [selectedAgency, setSelectedAgency] = useState(null);
  const [selectedDocs, setSelectedDocs] = useState([]);
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);

  const availableDocs = Object.keys(documents || {}).filter(key => documents[key]?.content);

  const toggleDocument = (docId) => {
    setSelectedDocs(prev => 
      prev.includes(docId) 
        ? prev.filter(d => d !== docId)
        : [...prev, docId]
    );
  };

  const selectAgency = (agency) => {
    setSelectedAgency(agency);
    // Auto-select required documents
    const requiredDocIds = [];
    agency.requirements.forEach(req => {
      const docId = Object.keys(DOCUMENT_NAMES).find(k => DOCUMENT_NAMES[k] === req);
      if (docId && availableDocs.includes(docId)) {
        requiredDocIds.push(docId);
      }
    });
    setSelectedDocs(requiredDocIds);
  };

  const generatePackage = async () => {
    if (!selectedAgency) {
      toast.error('Please select an agency');
      return;
    }
    if (selectedDocs.length === 0) {
      toast.error('Please select documents to include');
      return;
    }

    setGenerating(true);
    
    try {
      // Generate combined document content
      let packageContent = `
═══════════════════════════════════════════════════════════════
        STOLEN FUNDS EVIDENCE PACKAGE
        Prepared for: ${selectedAgency.fullName}
═══════════════════════════════════════════════════════════════

Case Number: ${caseData.case_number}
Case Title: ${caseData.case_title}
Victim: ${caseData.victim_name}
Amount Stolen: $${caseData.amount_stolen_usd?.toLocaleString() || 0} USD
Generated: ${new Date().toLocaleString()}

═══════════════════════════════════════════════════════════════

`;

      selectedDocs.forEach(docId => {
        const doc = documents[docId];
        if (doc?.content) {
          packageContent += `\n${'─'.repeat(60)}\n`;
          packageContent += `DOCUMENT: ${DOCUMENT_NAMES[docId]}\n`;
          packageContent += `${'─'.repeat(60)}\n\n`;

          doc.content.sections?.forEach(section => {
            packageContent += `## ${section.heading}\n\n`;
            packageContent += `${section.content}\n\n`;
          });
        }
      });

      packageContent += `
═══════════════════════════════════════════════════════════════
        END OF EVIDENCE PACKAGE
        
This document was generated by SafeNestt Investigation System.
For questions, contact: support@safenestt.com
═══════════════════════════════════════════════════════════════
`;

      // Download the package
      const blob = new Blob([packageContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = window.document.createElement('a');
      a.href = url;
      a.download = `${caseData.case_number}_Evidence_Package_${selectedAgency.id.toUpperCase()}.txt`;
      a.click();
      URL.revokeObjectURL(url);

      // Log submission
      await base44.entities.InvestigationCase.update(caseData.id, {
        agencies_contacted: [...(caseData.agencies_contacted || []), selectedAgency.name],
        submission_dates: {
          ...(caseData.submission_dates || {}),
          [selectedAgency.id]: new Date().toISOString()
        },
        last_activity: new Date().toISOString()
      });

      setGenerated(true);
      toast.success('Evidence package generated and downloaded');

      // Open agency website
      if (selectedAgency.url) {
        setTimeout(() => {
          window.open(selectedAgency.url, '_blank');
        }, 1500);
      }
    } catch (error) {
      toast.error('Failed to generate package');
      console.error(error);
    }
    
    setGenerating(false);
  };

  const openEmailTemplate = () => {
    if (!selectedAgency) return;

    const subject = encodeURIComponent(`Crypto Fraud Report - Case ${caseData.case_number}`);
    const body = encodeURIComponent(`
Dear ${selectedAgency.fullName},

I am submitting a formal complaint regarding cryptocurrency fraud.

CASE DETAILS:
- Case Number: ${caseData.case_number}
- Victim Name: ${caseData.victim_name}
- Amount Stolen: $${caseData.amount_stolen_usd?.toLocaleString() || 0} USD
- Fraud Type: ${caseData.fraud_type?.replace(/_/g, ' ')}
- Incident Date: ${caseData.incident_date ? new Date(caseData.incident_date).toLocaleDateString() : 'N/A'}

Please find the attached evidence package containing:
${selectedDocs.map(d => `- ${DOCUMENT_NAMES[d]}`).join('\n')}

I am available to provide additional information as needed.

Best regards,
${caseData.victim_name}
${caseData.victim_email || ''}
${caseData.victim_phone || ''}
    `.trim());

    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const content = (
    <div className="space-y-6">
      {/* Agency Selection */}
      <div>
        <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
          <Building2 className="w-5 h-5 text-cyan-400" />
          Select Federal Agency
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {FEDERAL_AGENCIES.map((agency) => {
            const Icon = agency.icon;
            const isSelected = selectedAgency?.id === agency.id;

            return (
              <Card 
                key={agency.id}
                onClick={() => selectAgency(agency)}
                className={`cursor-pointer transition-all ${
                  isSelected 
                    ? `bg-${agency.color}-500/20 border-${agency.color}-500/50` 
                    : 'bg-[#0f1419] border-cyan-500/10 hover:border-cyan-500/30'
                }`}
              >
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <div className={`w-10 h-10 rounded-lg bg-${agency.color}-500/20 flex items-center justify-center flex-shrink-0`}>
                      <Icon className={`w-5 h-5 text-${agency.color}-400`} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="text-white font-semibold">{agency.name}</h4>
                        {isSelected && <CheckCircle className="w-4 h-4 text-green-400" />}
                      </div>
                      <p className="text-gray-400 text-xs mb-2">{agency.description}</p>
                      <div className="flex flex-wrap gap-1">
                        {agency.requirements.map((req, i) => (
                          <Badge key={i} variant="outline" className="text-xs">
                            {req}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>

      {/* Document Selection */}
      {selectedAgency && (
        <div>
          <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            Select Documents to Include
          </h3>
          
          {availableDocs.length === 0 ? (
            <div className="p-6 bg-yellow-500/10 border border-yellow-500/20 rounded-lg text-center">
              <AlertTriangle className="w-8 h-8 text-yellow-400 mx-auto mb-2" />
              <p className="text-yellow-400 font-semibold">No documents generated yet</p>
              <p className="text-gray-400 text-sm mt-1">
                Generate case documents first before submitting to authorities
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {availableDocs.map((docId) => {
                const isSelected = selectedDocs.includes(docId);
                const isRequired = selectedAgency.requirements.includes(DOCUMENT_NAMES[docId]);

                return (
                  <div 
                    key={docId}
                    onClick={() => toggleDocument(docId)}
                    className={`p-3 rounded-lg border cursor-pointer transition-all flex items-center gap-3 ${
                      isSelected 
                        ? 'bg-cyan-500/20 border-cyan-500/50' 
                        : 'bg-[#0f1419] border-gray-600/30 hover:border-cyan-500/30'
                    }`}
                  >
                    <Checkbox checked={isSelected} />
                    <div className="flex-1">
                      <p className="text-white text-sm font-medium">{DOCUMENT_NAMES[docId]}</p>
                      {isRequired && (
                        <Badge className="mt-1 bg-orange-500/20 text-orange-400 border-orange-500/50 text-xs">
                          Required
                        </Badge>
                      )}
                    </div>
                    <CheckCircle className={`w-4 h-4 ${isSelected ? 'text-green-400' : 'text-gray-600'}`} />
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* Actions */}
      {selectedAgency && availableDocs.length > 0 && (
        <div className="flex flex-wrap gap-3">
          <Button
            onClick={generatePackage}
            disabled={generating || selectedDocs.length === 0}
            className="bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-600 hover:to-blue-700"
          >
            {generating ? (
              <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Generating...</>
            ) : (
              <><Download className="w-4 h-4 mr-2" />Generate & Download Package</>
            )}
          </Button>

          <Button
            onClick={openEmailTemplate}
            disabled={selectedDocs.length === 0}
            variant="outline"
            className="border-cyan-500/30 text-cyan-400"
          >
            <Mail className="w-4 h-4 mr-2" />
            Open Email Template
          </Button>

          {selectedAgency.url && (
            <Button
              onClick={() => window.open(selectedAgency.url, '_blank')}
              variant="outline"
              className="border-gray-500/30"
            >
              <Globe className="w-4 h-4 mr-2" />
              Open {selectedAgency.name} Portal
            </Button>
          )}
        </div>
      )}

      {/* Success Message */}
      {generated && (
        <div className="p-4 bg-green-500/10 border border-green-500/20 rounded-lg">
          <div className="flex items-start gap-3">
            <CheckCircle className="w-5 h-5 text-green-400 mt-0.5" />
            <div>
              <p className="text-green-400 font-semibold">Evidence Package Ready</p>
              <p className="text-gray-300 text-sm mt-1">
                Your evidence package has been downloaded. Follow these steps:
              </p>
              <ol className="text-gray-400 text-sm mt-2 list-decimal list-inside space-y-1">
                <li>Open the {selectedAgency.name} submission portal</li>
                <li>Fill out required complaint information</li>
                <li>Attach the downloaded evidence package</li>
                <li>Save any confirmation or case numbers</li>
              </ol>
            </div>
          </div>
        </div>
      )}
    </div>
  );

  if (isDialog) {
    return (
      <Dialog open onOpenChange={onClose}>
        <DialogContent className="bg-[#1a2332] border-cyan-500/20 text-white max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold text-white flex items-center gap-2">
              <Send className="w-6 h-6 text-red-400" />
              Send to Authorities
            </DialogTitle>
          </DialogHeader>
          {content}
        </DialogContent>
      </Dialog>
    );
  }

  return (
    <Card className="bg-gradient-to-br from-[#1a2332] to-[#0f1419] border-cyan-500/20">
      <CardHeader>
        <CardTitle className="text-white flex items-center gap-2">
          <Send className="w-5 h-5 text-red-400" />
          Submit to Federal Agencies
        </CardTitle>
      </CardHeader>
      <CardContent>{content}</CardContent>
    </Card>
  );
}