import React, { useState } from 'react';
import { base44 } from "@/api/base44Client";
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { 
    FileText, Download, RefreshCw, Briefcase, 
    ShieldCheck, AlertTriangle, Printer 
} from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";

export default function MasterCaseGenerator({ onClose }) {
    const [reportContent, setReportContent] = useState("");
    const [loading, setLoading] = useState(false);
    const [stats, setStats] = useState(null);

    const generateReport = async () => {
        setLoading(true);
        try {
            const res = await base44.functions.invoke('generateMasterCaseReport', {});
            if (res.data.success) {
                setReportContent(res.data.reportHtml);
                setStats(res.data.stats);
                toast.success("Master Case Report Generated");
            } else {
                toast.error(res.data.error || "Failed to generate report");
            }
        } catch (error) {
            toast.error("Error generating report");
            console.error(error);
        }
        setLoading(false);
    };

    const handlePrint = () => {
        const printWindow = window.open('', '_blank');
        printWindow.document.write(`
            <html>
                <head>
                    <title>Master Case Report - SafeNestT</title>
                    <script src="https://cdn.tailwindcss.com"></script>
                    <style>
                        body { padding: 40px; font-family: sans-serif; }
                        @media print { body { padding: 0; } }
                    </style>
                </head>
                <body>
                    ${reportContent}
                    <div class="mt-8 pt-8 border-t text-sm text-gray-500">
                        Generated by SafeNestT Intelligence System on ${new Date().toLocaleDateString()}
                    </div>
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.print();
    };

    return (
        <Card className="w-full bg-[#0f1419] border-cyan-500/20 text-white shadow-2xl">
            <CardHeader className="border-b border-gray-800">
                <div className="flex items-center justify-between">
                    <div>
                        <CardTitle className="text-xl flex items-center gap-2">
                            <Briefcase className="w-6 h-6 text-cyan-400" />
                            Master Case Intelligence Report
                        </CardTitle>
                        <p className="text-sm text-gray-400 mt-1">
                            Consolidate all your cases into a single law-enforcement ready file.
                        </p>
                    </div>
                    <div className="flex gap-2">
                        {reportContent && (
                            <Button variant="outline" onClick={handlePrint} className="border-gray-700 text-gray-300">
                                <Printer className="w-4 h-4 mr-2" /> Print / Save PDF
                            </Button>
                        )}
                        <Button 
                            onClick={generateReport} 
                            disabled={loading}
                            className="bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-700 hover:to-blue-700"
                        >
                            {loading ? <RefreshCw className="w-4 h-4 animate-spin mr-2" /> : <FileText className="w-4 h-4 mr-2" />}
                            {reportContent ? 'Regenerate Report' : 'Generate Master Report'}
                        </Button>
                    </div>
                </div>
            </CardHeader>
            <CardContent className="p-0">
                {stats && (
                    <div className="grid grid-cols-3 gap-px bg-gray-800 border-b border-gray-800">
                        <div className="p-4 bg-[#1a2332]">
                            <p className="text-xs text-gray-400">Total Cases</p>
                            <p className="text-xl font-bold text-white">{stats.caseCount}</p>
                        </div>
                        <div className="p-4 bg-[#1a2332]">
                            <p className="text-xs text-gray-400">Total Loss</p>
                            <p className="text-xl font-bold text-red-400">${stats.totalLoss.toLocaleString()}</p>
                        </div>
                        <div className="p-4 bg-[#1a2332]">
                            <p className="text-xs text-gray-400">Identified Wallets</p>
                            <p className="text-xl font-bold text-cyan-400">{stats.walletCount}</p>
                        </div>
                    </div>
                )}
                
                <div className="p-6 min-h-[500px] bg-white text-black">
                    {reportContent ? (
                        <ReactQuill 
                            theme="snow" 
                            value={reportContent} 
                            onChange={setReportContent}
                            className="h-[600px] pb-12"
                            modules={{
                                toolbar: [
                                    [{ 'header': [1, 2, 3, false] }],
                                    ['bold', 'italic', 'underline', 'strike'],
                                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                                    ['clean']
                                ]
                            }}
                        />
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-gray-400 py-20">
                            <ShieldCheck className="w-16 h-16 mb-4 opacity-20" />
                            <p className="text-lg font-medium">Ready to generate report</p>
                            <p className="text-sm max-w-md text-center mt-2 opacity-60">
                                This tool will scan all your submitted cases, evidence, and blockchain data to create a unified timeline and master investigation file.
                            </p>
                            <Button 
                                variant="outline" 
                                onClick={generateReport}
                                className="mt-8 border-gray-200 text-gray-600 hover:bg-gray-50"
                            >
                                Start Generation
                            </Button>
                        </div>
                    )}
                </div>
            </CardContent>
        </Card>
    );
}