import React from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import EmptyState from "@/components/platform/EmptyState";
import SectionHeader from "@/components/platform/SectionHeader";

const REPORT_TYPES = {
  investigation_report: "Investigation Report",
  evidence_report: "Evidence Report",
  blockchain_trace_report: "Blockchain Trace Report",
  executive_summary: "Executive Summary",
  finding_report: "Finding Report",
};

export default function ReportsCenter() {
  const { data: reports = [], isLoading } = useQuery({
    queryKey: ["all-reports"],
    queryFn: () => base44.entities.InvestigationReport.list("-created_date", 200),
  });

  return (
    <div className="p-6 lg:p-8 space-y-6">
      <SectionHeader title="Reports Center" description="All investigation reports across all cases. Reports are generated by Hermes and stored for export and archival." icon={FileText} />

      {isLoading ? (
        <EmptyState variant="loading" title="Loading reports…" />
      ) : reports.length === 0 ? (
        <EmptyState variant="empty" icon={FileText} title="No reports yet" description="Reports are generated by Hermes from the Investigation Workspace. Open a case and generate a report to see it here." action={<Link to="/CasesManagement"><Button size="sm" className="bg-cyan-600 hover:bg-cyan-700">Go to Cases</Button></Link>} />
      ) : (
        <div className="rounded-lg border border-white/10 divide-y divide-white/5">
          {reports.map((report) => (
            <div key={report.id} className="flex items-center gap-3 p-4 hover:bg-white/[0.02] transition-colors">
              <div className="w-9 h-9 rounded-md border border-white/10 bg-white/[0.02] flex items-center justify-center shrink-0">
                <FileText className="w-4 h-4 text-gray-400" />
              </div>
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium text-white truncate">{report.title}</p>
                <p className="text-xs text-gray-500 truncate">{REPORT_TYPES[report.report_type] || report.report_type} • {report.generated_by} • {report.generated_date ? new Date(report.generated_date).toLocaleDateString() : ""}</p>
              </div>
              <Badge variant="outline" className="border-cyan-500/30 text-cyan-400 text-[10px] capitalize">{report.status}</Badge>
              <Link to={`/InvestigationWorkspace?case_id=${report.case_id}`}>
                <Button size="sm" variant="outline" className="border-white/15 text-gray-200">Open</Button>
              </Link>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}