import React, { useState } from "react";
import { FlaskConical, CheckCircle2, XCircle, Clock, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import HermesPanel from "@/components/platform/HermesPanel";
import { HermesAPI } from "@/lib/hermesClient";
import { SeverityBadge, ConfidenceBadge, FINDING_STATUS_STYLES } from "@/components/platform/investigationStyles";
import { logAuditEvent } from "@/lib/auditLogger";
import { toast } from "sonner";

const SUB_TABS = [
  { key: "findings", label: "Findings", icon: FlaskConical },
  { key: "review", label: "Review Center", icon: CheckCircle2 },
];

export default function FindingsTab({ caseId, hermesState }) {
  const [sub, setSub] = useState("findings");
  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 border-b border-white/10 pb-px">
        {SUB_TABS.map((t) => (
          <button key={t.key} onClick={() => setSub(t.key)}
            className={`flex items-center gap-1.5 px-3 py-2 text-sm rounded-t-md transition-colors ${sub === t.key ? "text-cyan-400 border-b-2 border-cyan-400 bg-cyan-500/[0.04]" : "text-gray-400 hover:text-gray-200"}`}>
            <t.icon className="w-4 h-4" />{t.label}
          </button>
        ))}
      </div>
      <HermesPanel caseId={caseId} hermesState={hermesState} queryKey="findings" fetcher={HermesAPI.getFindings}
        emptyTitle="No findings yet" emptyDescription="Findings are generated by Hermes during investigation. AI findings are NOT automatically verified — they start as 'proposed' and require investigator review."
        render={(data) => {
          const findings = Array.isArray(data) ? data : data?.findings || [];
          const display = sub === "review" ? findings.filter((f) => f.status === "proposed" || f.status === "under_review") : findings;
          if (display.length === 0) return <div className="rounded-lg border border-white/10 p-8 text-center"><p className="text-sm text-gray-500">{sub === "review" ? "No findings require review." : "No findings returned by Hermes."}</p></div>;
          return <FindingsList findings={display} caseId={caseId} hermesState={hermesState} />;
        }} />
    </div>
  );
}

function FindingsList({ findings, caseId, hermesState }) {
  const [reviewFinding, setReviewFinding] = useState(null);
  return (
    <>
      <div className="space-y-3">
        {findings.map((finding, i) => {
          const statusCls = FINDING_STATUS_STYLES[finding.status] || FINDING_STATUS_STYLES.proposed;
          return (
            <div key={i} className="rounded-lg border border-white/10 bg-white/[0.02] p-4">
              <div className="flex items-start gap-3">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap mb-1">
                    <p className="text-sm font-medium text-white">{finding.title}</p>
                    <SeverityBadge severity={finding.severity} />
                    <ConfidenceBadge confidence={finding.confidence} />
                    <Badge variant="outline" className={`text-[10px] capitalize ${statusCls}`}>{(finding.status || "proposed").replace(/_/g, " ")}</Badge>
                  </div>
                  {finding.description && <p className="text-xs text-gray-400">{finding.description}</p>}
                  <div className="flex items-center gap-3 mt-2 text-xs text-gray-500">
                    {finding.category && <span className="capitalize">{finding.category.replace(/_/g, " ")}</span>}
                    {finding.source && <span>Source: {finding.source}</span>}
                    {finding.created_date && <span>{new Date(finding.created_date).toLocaleString()}</span>}
                  </div>
                </div>
                {(finding.status === "proposed" || finding.status === "under_review") && (
                  <Button size="sm" variant="outline" onClick={() => setReviewFinding(finding)} className="border-cyan-500/30 text-cyan-400 shrink-0">Review</Button>
                )}
              </div>
            </div>
          );
        })}
      </div>
      {reviewFinding && <ReviewDialog finding={reviewFinding} caseId={caseId} hermesState={hermesState} onClose={() => setReviewFinding(null)} />}
    </>
  );
}

function ReviewDialog({ finding, caseId, hermesState, onClose }) {
  const [action, setAction] = useState("");
  const [notes, setNotes] = useState("");
  const [busy, setBusy] = useState(false);

  const submit = async (act) => {
    setBusy(act);
    try {
      const res = await HermesAPI.submitFindingReview(caseId, finding.id || finding.finding_id, { action: act, notes });
      if (res.status === "ok") {
        await logAuditEvent({ action: `finding_${act}`, objectType: "finding", objectId: finding.id, caseId, description: `Finding "${finding.title}" ${act}: ${notes}` });
        toast.success(`Finding ${act}`);
        onClose();
      } else if (res.status === "not_connected" || res.status === "backend_unavailable") {
        toast.error("Hermes backend unavailable — review could not be submitted.");
      } else {
        toast.error("Review failed: " + (res.error || "unknown"));
      }
    } catch (e) { toast.error("Failed: " + (e.message || e)); }
    finally { setBusy(null); }
  };

  return (
    <Dialog open onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="bg-[#0f1419] border-white/15 text-white max-w-lg">
        <DialogHeader><DialogTitle className="text-white">Review Finding</DialogTitle></DialogHeader>
        <div className="space-y-3">
          <div className="rounded-lg border border-white/10 bg-black/30 p-3">
            <p className="text-sm font-medium text-white">{finding.title}</p>
            {finding.description && <p className="text-xs text-gray-400 mt-1">{finding.description}</p>}
            <div className="flex gap-2 mt-2"><SeverityBadge severity={finding.severity} /><ConfidenceBadge confidence={finding.confidence} /></div>
          </div>
          {(finding.evidence_refs?.length > 0 || finding.entity_refs?.length > 0 || finding.transaction_refs?.length > 0) && (
            <div className="text-xs space-y-1">
              {finding.evidence_refs?.length > 0 && <p className="text-gray-400">Evidence: {finding.evidence_refs.length} reference(s)</p>}
              {finding.entity_refs?.length > 0 && <p className="text-gray-400">Entities: {finding.entity_refs.length} reference(s)</p>}
              {finding.transaction_refs?.length > 0 && <p className="text-gray-400">Transactions: {finding.transaction_refs.length} reference(s)</p>}
            </div>
          )}
          <div><Textarea placeholder="Review notes…" value={notes} onChange={(e) => setNotes(e.target.value)} className="bg-[#0a0f1a] border-white/10 text-white min-h-[80px]" /></div>
        </div>
        <DialogFooter className="flex-wrap gap-2">
          <Button variant="outline" onClick={() => submit("verify")} disabled={!!busy} className="border-green-500/30 text-green-400">{busy === "verify" ? <Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> : <CheckCircle2 className="w-4 h-4 mr-1.5" />}Verify</Button>
          <Button variant="outline" onClick={() => submit("reject")} disabled={!!busy} className="border-red-500/30 text-red-400">{busy === "reject" ? <Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> : <XCircle className="w-4 h-4 mr-1.5" />}Reject</Button>
          <Button variant="outline" onClick={() => submit("request_more")} disabled={!!busy} className="border-amber-500/30 text-amber-400">{busy === "request_more" ? <Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> : <Clock className="w-4 h-4 mr-1.5" />}Request More</Button>
          <Button variant="outline" onClick={onClose} className="border-white/15 text-gray-200">Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}